This is makeindex, version 2.15 [MiKTeX 2.9.6350 64-bit] (kpathsea + Thai support).
Scanning style file ./diss.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file diss.acn....done (316 entries accepted, 0 rejected).
Sorting entries.....done (2955 comparisons).
Generating output file diss.acr....done (187 lines written, 0 warnings).
Output written in diss.acr.
Transcript written in diss.alg.
