This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file ./diss.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file diss.acn....done (320 entries accepted, 0 rejected).
Sorting entries.....done (2842 comparisons).
Generating output file diss.acr....done (188 lines written, 0 warnings).
Output written in diss.acr.
Transcript written in diss.alg.
